spring.application.name=tedee-automation

# Tedee settings
tedee.lock.id=0
tedee.sync.interval-ms=60000

# Telegram settings
telegram.bot.token=
telegram.chat.id=

# Actuator
management.endpoints.web.exposure.include=health,info
